version: '3.8'

networks:
    localdev:
        name: localdev

services:
    php-fpm73:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - .:/var/www/html
            - ./dockerConf/php:/usr/local/etc/php
            - ./dockerConf/supervisor:/etc/supervisor/conf.d
        ports:
            - '9000:9000'
        networks:
            - localdev
