version: '3.8'

networks:
    localdev:
        name: localdev

services:
    php-fpm73:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - '9000:9000'
        networks:
            - localdev
